lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
theme: jekyll-theme-minimal
title: Aautomation Hub
description: Bookmark this to learn more on Automation Testing.
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
